# Generated by Django 3.1.6 on 2021-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_auto_20210210_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en instance', 'en instance'), ('non livré', 'non livré'), ('livré', 'livré')], max_length=255),
        ),
    ]
